services:
    prometheus:
      command:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/prometheus
        - --web.enable-remote-write-receiver
        - --web.enable-admin-api
        - --web.enable-lifecycle
        - --storage.tsdb.retention.time=7d
      container_name: prometheus
      image: prom/prometheus:latest
      env_file:
          - .env
      networks:
        shared: null
      ports:
      - protocol: tcp
        published: 9090
        target: 9090
      restart: always
      volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    telegraf:
        build: ./telegraf
        container_name: telegraf
        links:
            - prometheus
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /proc:/hostfs/proc
        privileged: true
        restart: always
        env_file:
            - .env
        networks:
            shared: null
    grafana:
        build: ./grafana
        container_name: grafana
        environment:
            GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /opt/grafana/dashboards/TunnelStats.json
        ports: 
            - ${GRAFANA_PORT}:${GRAFANA_PORT}
        links:
            - prometheus
        volumes:
            - /var/lib/grafana
            - /var/log/grafana
            - /var/lib/grafana/plugins
            - ./grafana/provisioning/datasources/tunnel/:/etc/grafana/provisioning/datasources/:ro
        restart: always
        env_file:
            - .env
        networks:
            shared: null
networks:
    shared: {}
